- .gitignore
- gruntfile.js
- package.json
- src/scripts/default.js
- src/scripts/translate.js
- src/styles/default.scss
- templates/settings.php
Add initial files for frontend development.
> Initial frontend commit (setup)

- Makefile.release
`make -f Makefile.release dist`
> Add makefile for build, package and sign

- .eslintrc.json
- package.json
- src/config.json
- src/scripts/Viewer.vue
- src/scripts/ViewerControls.vue
- src/scripts/default.js
- src/scripts/helper.js
- src/scripts/init.js
- src/styles/_swiper.scss
- src/styles/_viewer.scss
- src/styles/default.scss
Loads next and previous files on demand.
- Closes https://github.com/owncloud/files_mediaviewer/issues/7
- Closes https://github.com/owncloud/files_mediaviewer/issues/8
> Add swiper functionality

- README.md
See this for a preview: https://github.com/owncloud/files_mediaviewer/tree/add-gif-to-readme
> Add the ani gif to the readme file

- .eslintrc.json
- gruntfile.js
- package.json
- src/scripts/Viewer.vue
- src/scripts/ViewerControls.vue
- src/scripts/default.js
- src/scripts/helper.js
- Fix code styling
- Minified dependencies for production build
- Add JS und Vue Linting
> Minor code-style fixes, add custom import resolve for production build

- package.json
- src/scripts/Viewer.vue
- src/scripts/ViewerControlsMeta.vue
- src/scripts/helper.js
- src/styles/_base.scss
Allow media to be viewed in public links.
Fixes https://github.com/owncloud/files_mediaviewer/issues/17
Fixes https://github.com/owncloud/files_mediaviewer/issues/37
Closes https://github.com/owncloud/files_mediaviewer/pull/39
> Public file view

- appinfo/info.xml
Added screenshot
Icon will follow
> Add screenshot

- src/styles/_viewerControls.scss
The title says it all!
Fixes: https://github.com/owncloud/files_mediaviewer/issues/56
> Improve play button vis. on bright background

- src/scripts/Viewer.vue
- src/scripts/ViewerControls.vue
- src/scripts/ViewerControlsImage.vue
- src/scripts/ViewerControlsMeta.vue
- src/scripts/ViewerControlsVideo.vue
- src/scripts/helper.js
* Close on clicking outside of slider
* add global closeViewer() method
closes: https://github.com/owncloud/files_mediaviewer/issues/53
> Close on clicking outside of slider

- src/config.json
- src/scripts/default.js
- src/scripts/init.js
- src/scripts/setup.js
- src/styles/_viewer.scss
The title says it all ;-)
Fixes: https://github.com/owncloud/files_mediaviewer/issues/65
For those who test, don't forget to enable ImageMagic for SVG support.
> Support images based on enabled preview providers

- gruntfile.js
- package.json
- src/scripts/Viewer.vue
- src/scripts/default.js
- src/scripts/ie11routerfix.js
- src/styles/_viewerControls.scss
- Add browser targets to babelify
- Update dependencies
- Fix CSS for IE
- Add vue-router IE11 workaround
Fixes https://github.com/owncloud/files_mediaviewer/issues/79
> Add IE11 vue-router fix

- gruntfile.js
- package.json
- src/styles/default.scss
- Removed PureCSS dependency
Will fix IE11 and Edge layout issues.
> [RC 1.0.0] Add postCSS for vendor prefixing

- src/styles/_base.scss
Fixes: https://github.com/owncloud/files_mediaviewer/issues/47
> [RC 1.0.0] fix involuntary text selection

- package.json
- src/scripts/Viewer.vue
- src/scripts/ViewerControls.vue
- src/scripts/ViewerControlsImage.vue
- src/scripts/ViewerControlsVideo.vue
- src/scripts/default.js
- src/scripts/helper.js
- src/scripts/store.js
Reset the store contents when deactivating the swiper.
Fixes: #74
Fixes: #75
Fixes: #76
Fixes: #77
> [RC 1.0.0] Reset store on deactivation

- CHANGELOG.md
- Makefile
- appinfo/info.xml
- gruntfile.js
- package.json
- src/scripts/Viewer.vue
- src/scripts/ViewerControls.vue
- src/scripts/ViewerControlsImage.vue
- src/scripts/ViewerControlsVideo.vue
- src/scripts/default.js
- src/scripts/getEventListeners.js
- src/scripts/helper.js
- src/scripts/init.js
- src/scripts/store.js
- src/styles/_base.scss
- src/styles/default.scss
closes https://github.com/owncloud/files_mediaviewer/issues/15
> Release 1.0.0  🎉

- src/scripts/ViewerControlsVideo.vue
Closes: https://github.com/owncloud/files_mediaviewer/issues/94
> Add fullscreen support for MSIE, Edge and Safari

- src/styles/_base.scss
Place the gallery view one level higher. Fixes https://github.com/owncloud/files_mediaviewer/issues/135
> Mobile browser view fix

- CHANGELOG.md
- appinfo/info.xml
- Changelog
- Bump Version number
> Release 1.0.1

- src/scripts/Viewer.vue
Fixes https://github.com/owncloud/files_mediaviewer/issues/148
> Encode # in media URI

- src/styles/_viewerControls.scss
Fixes: https://github.com/owncloud/files_mediaviewer/issues/137
> Fix media controls on small devices

- package.json
- src/scripts/ViewerControlsImage.vue
- src/scripts/ViewerControlsVideo.vue
- src/scripts/setup.js
Add notification if video playback fails.
Fixes https://github.com/owncloud/files_mediaviewer/issues/35
> Add notification on playback error

- src/config.json
- src/scripts/init.js
Fixes https://github.com/owncloud/files_mediaviewer/issues/169 Add Support for playing Apple Quicktime (*.mov)
> Update config.json to support mimetype video/quicktime

- CHANGELOG.md
- appinfo/info.xml
Closes https://github.com/owncloud/files_mediaviewer/issues/192
> Merge back Release 1.0.2

- Makefile
- l10n/.tx/config
- l10n/Makefile
- l10n/de.js
- l10n/de.json
- package.json
- src/scripts/ViewerControlsNavigate.vue
- src/scripts/helper.js
- yarn.lock
> Add l10n support

- .drone.star
- .gitignore
A very minimalist drone setup - better then nothing. 
- build the app
- try to extract translation strings
> Add drone.star

- Makefile
https://github.com/owncloud/files_mediaviewer/issues/220#issuecomment-656510962
> Include l10n in tarball

- src/scripts/init.js
fixes https://github.com/owncloud/files_mediaviewer/issues/337
Before: 
After:
> Add icon and correct text in the file actions menu

- CHANGELOG.md
- appinfo/info.xml
Merge release branch back to master.
Closes #324
> Release 1.0.4

- CHANGELOG.md
- appinfo/info.xml
> Release 1.0.5

- .drone.star
it is better to use directory references from the dir var, rather than using the hard-coded values in every use case.
- https://github.com/owncloud/QA/issues/734#issue-1173320353
- CI
> [full-ci]Use directory references from global dir variable in drone.star file 
